### ISSUE TITLE
Cobalt recipe missing from botany pots (with stopgap workaround)

### ISSUE THREAD

**Issue by DarkHelmet433** [North-West-Wind/SkyFarmEssential#10]
BotanyPots is missing a recipe and drops for the cobalt seed.

As a stopgap I added a crop for it via CT but this is definitely not the best way.   I created botany_cobalt.zs alongside botany_crops.zs with
```
import mods.botanypots.ZenCrop;
val crops = <recipetype:botanypots:crop>;

val skyfarm_cobalt = crops.create("skyfarm:crops/cobalt", <item:mysticalagriculture:cobalt_seeds>, <blockstate:mysticalagriculture:cobalt_crop>, 4000, "dirt");
skyfarm_cobalt.addDrop(<item:mysticalagriculture:cobalt_essence>, 0.5, 4);
skyfarm_cobalt.addDrop(<item:mysticalagriculture:cobalt_seeds>, 0.2);
skyfarm_cobalt.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
```

However, this has the wrong model/texture for the animated crop growth.  If it was done in json data it could follow the example from https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/mysticalagriculture/recipes/crops/netherite.json#L23 and use properties age 7 for the model.  I couldn't find a way to use properties in CT but it was enough for me.

Presumably Mystical and BotanyPots will update but an interim crop / drops for the pots would be nice.  A proper json definition could have the right display model but I'm including my stopgap kludge in case it's useful to somebody.

**Comment by gaminggirl** [comment]
More seeds are missing Botany Pot recipies, Nitro, Hepatizon, Queens Slime, Manyullyn, Ravager, Fiery Ingot, Knightmetal, Fluorite, Rose Gold, Cobalt, Ironwood, Steeleaf, Pig Iron, Slimesteel, Tinker's Bronze, Apatite, Livingwood, Livingrock, Zombified Piglin, Piglin, Elementium, Gaia Spirit, Piglin Brute are the ones I have seen so far...

**Comment by North-West-Wind** [comment]
Added them in Sky Farm 1.1.0
