### ISSUE TITLE
Overworld Void Shifter - Nether falling upwards

### ISSUE THREAD

**Issue by gaminggirl** [North-West-Wind/SkyFarmEssential#11]
Whenever I put the Overworld Void Shifter - nether boots on I start going up in the sky and can't get down to fall into the void so I can get to the nether. They worked before but now they just take me up up up hundreds of blocks

**Comment by jackskely** [comment]
just sneak to cancel the effect.

**Comment by gaminggirl** [comment]
Solves the problem, but is it really intended for you to go up in the sky every time you oput the boots on?

**Comment by North-West-Wind** [comment]
Yes, or how do you think you are gonna get back up to your island?

**Comment by gaminggirl** [comment]
I am on my island when I put the boots on to go to the nether.
