### ISSUE TITLE
An issue with RecipeStage mod

### ISSUE THREAD

**Issue by 4dam3k** [North-West-Wind/SkyFarmEssential#2]
![image](https://user-images.githubusercontent.com/66412368/123677622-a3f4bb00-d845-11eb-9a43-b3d8bfffd9a5.png)

I unlocked all of essence from mystical agriculture with points from Parabox but after trying to craft them this happened

**Comment by North-West-Wind** [comment]
This is a known issue. Staged recipes don't work for some mods, and will have this error message.
I cannot fix this yet, so let's leave this open.

**Comment by North-West-Wind** [comment]
In Sky Farm 1.1.0, I implemented my own Recipe Stages. Now you should be able to craft staged recipes in machines.
This is still very experimental, so expect bugs.
