### ISSUE TITLE
Can't join server after press and hold the Shift key in nether.

### ISSUE THREAD

**Issue by liuseniubi** [North-West-Wind/SkyFarmEssential#3]
Can't join server after press and hold the Shift key in nether.
Server log is here: 
[latest.log](https://github.com/North-West-Wind/SkyFarmEssential/files/6742865/latest.log)

**Comment by North-West-Wind** [comment]
Are you using the latest version?

**Comment by liuseniubi** [comment]
No, but I'll try it later.

**Comment by liuseniubi** [comment]
Same issue using the latest version.

**Comment by North-West-Wind** [comment]
Forgot to tell you but this is fixed in the latest update
