### ISSUE TITLE
Mystical Agriculture Infusion Recipes not working 

### ISSUE THREAD

**Issue by CubicalDisaster** [North-West-Wind/SkyFarmEssential#30]
I had a problem with the steel recipe in the infusion altar but after trying multiple times it finally went through. I can't get quartz enriched seeds to go through the process. I am running the latest version and couldn't get it to work in the past 2 version
![2021-10-06_18 39 23](https://user-images.githubusercontent.com/71413718/136299093-f8a42c07-2027-4f7b-be6a-35cff8da5260.png)
s
![2021-10-06_18 46 02](https://user-images.githubusercontent.com/71413718/136299117-f86fbb4e-6d51-4212-a006-79c469a3bdbf.png)
.

**Comment by eloisemyers** [comment]
They were working for me but now I can't do anything above tier 1

**Comment by North-West-Wind** [comment]
Use Mekanism's fluid tank to carry them around, or attach a faucet to the basin.

Also this issue is resolved after updating Mystical Agriculture.
