### ISSUE TITLE
Can't autocraft Staged recipes

### ISSUE THREAD

**Issue by JM4000** [North-West-Wind/SkyFarmEssential#4]
No matter the method, you can't autocraft staged recipes, even when unlocked.
Cyclic autocrafter, rftools, refined storage (I still have to try AE2) are all the same.
If you try to make a RS pattern, it's marked as faulty, because "recipe has no output".

**Comment by North-West-Wind** [comment]
This is a known issue.
There is another one about it so I will close this one and redirect you to #2
