### ISSUE TITLE
working Optifine versions?

### ISSUE THREAD

**Issue by ALainxD** [North-West-Wind/SkyFarmEssential#7]
Hey i really like the Pack!

But sadly i really can't play without some shaders anymore, the game looks just a bit too outdated in my opinion.

So i was trying to get Optifine to work, but sadly i couldn't get it to work.

I tried Optifine versions: 
OptiFine 1.16.5 HD U G6
OptiFine 1.16.5 HD U G7
OptiFine 1.16.5 HD U G8

with and without combination of Optiforge (which should make compatibility a bit easier)
OptiForge-MC1.16.5-0.5.5

Sadly the game doesn't give a crash report in the game files, minecraft just closes and say: Game crashed ... Exit Code: 0 

I think it has something to do with the Forge version used, but i'm not sure... the game won't start with lower Forge version than 36.1.10 because appliedenergistics2 needs 36.1.10 or above.

Would be nice if anyone can help me out ... i know Optifne is probably not supported with the modpack but since i'm probably not the only one with the need of Optifne it would be nice to just leave the issue open until anyone has a solution for it.

Thank you
- Alain

**Comment by North-West-Wind** [comment]
Optifine doesn't work because we added Sodium Reforged, hoping to have better performance on both client and server.
Sodium Reforged stated they are not compatible with Optifine.
