### ISSUE TITLE
Storage advancements tab uses minecraft:chest trigger but Quark replaces chests.

### ISSUE THREAD

**Issue by DarkHelmet433** [North-West-Wind/SkyFarmEssential#9]
This caused me quite a bit of confusion.  I resorted to looking at the source code and even then I was confused when it required a chest, but I was holding one.

Then I noticed that Quark had replaced the chests and I hadn't noticed I was getting a quark:oak_chest with the standard recipes.

Suggestion:  replace all the `"item": "minecraft:chest"` triggers with a tag so that any chest will work, perhaps `"tag": "forge:chests"`

As it stands today, it's rather confusing for somebody who doesn't know what the trigger is.  The tab's grid is hidden from you even as you unlock random advancements that you can't even see until you trip over them.

**Comment by North-West-Wind** [comment]
Fixed in Sky Farm 1.1.0
